services:
  - type: web
    name: cosproject
    env: python
    buildCommand: |
      pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn cosproject.wsgi:application --bind 0.0.0.0:$PORT
    build:
      pythonVersion: 3.12.3
    staticPublishPath: staticfiles

static:
  - path: staticfiles
    urlPrefix: /static/