services:
  - type: web
    name: cosproject
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn cosproject.wsgi:application
    build:
      pythonVersion: 3.12.3